name: CI
on:
  push:
    branches: [main]
  pull_request: [main]
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Type Check
        run: yarn typecheck

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
